### PR TITLE
Feat/Refactor datasource matching

### PR DESCRIPTION
**Pull request by peshence**
- unify match functions across the datasources into the parent class
- unify repr functions
- unify conversion to mars request
- unify date checking #72 
- move datasource matching loop into collections
- add coercion to all sources
- in the process fix
  - expver formatting issues
  - array value matching issues
  - extraneous match failure messages ot users removed #92 
  - duplicate entries error message #111 
- small cleanup and some type hints added

### CODE REVIEW

**Comment by peshence** [comment]
> I'm not sure I understood how the date check works but it could be useful in our case as the FDB is only setup to store data of the last 24 hours

@cfkanesan  The date check is effectively set up as an age limit. So it can be e.g. <24h (inclusive, so really it's <=, 24h or newer) or >2d (exclusive, older then 2 days)

File: polytope_server/common/coercion.py [hunk 1]
```diff
@@ -0,0 +1,262 @@
...
+            try:
+                date_obj = datetime.strptime(value_stripped, "%Y-%m-%d")
+                return date_obj.strftime("%Y%m%d")
+            except ValueError:
+                raise CoercionError("Invalid date format, expected YYYYMMDD or YYYY-MM-DD.")
+    else:
+        raise CoercionError("Invalid date format, expected YYYYMMDD or YYYY-MM-DD.")
+
+
+def coerce_step(value: Any) -> str:
```
[the remark this answers is not in the document]
Comment (peshence) [reply polytope_server/common/coercion.py:120]: that is surprising to me, please discuss with James at the meeting

[the remark this answers is not in the document]
Comment (jameshawkes) [reply polytope_server/common/coercion.py:120]: we need to support this, we'll have subhourly soon too

[the remark this answers is not in the document]
Comment (jameshawkes) [reply polytope_server/common/coercion.py:120]: (this can be added in a later PR, not needed immediately)

**Comment by cfkanesan** [comment]
```
Traceback (most recent call last):
File "/app/polytope_server/worker/worker.py", line 195, in run
 self.future.result(0)
File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
 return self.__get_result()
File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
 raise self._exception
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
 result = self.fn(*self.args, **self.kwargs)
File "/otel-auto-instrumentation-python/opentelemetry/instrumentation/threading/__init__.py", line 143, in wrapped_func
 return original_func(*func_args, **func_kwargs)
File "/app/polytope_server/worker/worker.py", line 238, in process_request
 datasource = collection.dispatch(request, input_data)
File "/app/polytope_server/common/collection.py", line 76, in dispatch
 ds.dispatch(request, input_data)
File "/app/polytope_server/common/datasource/datasource.py", line 177, in dispatch
 success = self.retrieve(request)
File "/app/polytope_server/common/datasource/polytope.py", line 129, in retrieve
 self.output = polytope_mars.extract(r)
File "/usr/local/lib/python3.11/site-packages/polytope_mars/api.py", line 151, in extract
 result = self.api.retrieve(preq)
File "/usr/local/lib/python3.11/site-packages/polytope_feature/polytope.py", line 76, in retrieve
 self.datacube.get(request_tree, self.context)
File "/usr/local/lib/python3.11/site-packages/polytope_feature/datacube/backends/fdb.py", line 155, in get
 self.assign_fdb_output_to_nodes(iterator, complete_fdb_decoding_info)
File "/usr/local/lib/python3.11/site-packages/polytope_feature/datacube/backends/fdb.py", line 330, in assign_fdb_output_to_nodes
 if len(result.values) == 0:
AttributeError: 'list' object has no attribute 'values'
``` 
I get this traceback when attempting to request a feature extraction

**Comment by cfkanesan** [comment]
polytope: 1.1.1
pygribjump: 0.8.1

**Comment by cfkanesan** [comment]
Is it backwards compatible? I have to deploy the matching gribjump server and it's straightforward but not exactly a trivial amount of work that I would like to only do once if possible.

**Comment by mathleur** [comment]
Unfortunately it's not backwards compatible, all versions of polytope >= 1.1.0 will only work with pygribjump >= 0.10.0 and vice versa

File: polytope_server/common/coercion.py [hunk 2]
```diff
@@ -0,0 +1,262 @@
...
+            else:
+                raise CoercionError("Invalid type, expected integer step or step range.")
+    else:
+        raise CoercionError("Invalid type, expected integer or string.")
+
+
+def coerce_number(value: Any) -> str:
+    if isinstance(value, int):
+        if value <= 0:
+            raise CoercionError("Number must be a positive value.")
```
[the remark this answers is not in the document]
Comment (peshence) [reply polytope_server/common/coercion.py]: added

**Comment by cfkanesan** [comment]
Thanks for the info @mathleur 

I can see that we already moved to the 1.1.1 version of polytope on our main branch so I'll proceed with the upgrade
